services:
  mongodb:
    image: mongo:5.0.31-focal
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  graphhopper:
    image: israelhikingmap/graphhopper:10.0
    container_name: graphhopper
    ports:
      - "8989:8989"
    environment:
      - JAVA_OPTS=-Xmx4g
      - GH_GRAPH_LOCATION=data/graph-cache
      - GH_DATA_LOCATION=data/albania-latest.osm.pbf
      - GH_WEB_LISTENER_PORT=8989

    volumes:
      - ./graphhopper:/data
    command: >
      sh -c "graphhopper.sh web /data/albania-latest.osm.pbf"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 6g

volumes:
  mongodb_data:
    driver: local
